colorscheme badwolf 
syntax enable
set tabstop=4
set expandtab 
set number
set showcmd 
set cursorline
filetype indent on
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch 
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent
set autoindent
set smartindent
set ruler
set backspace=indent,eol,start
set title
set scrolloff=3
set history=1000
